### ISSUE TITLE
Push to Ansible Galaxy

### ISSUE THREAD

**Issue by chadmf** [ansible-collections/community.cip#13]

**Comment by maxamillion** [comment]
https://galaxy.ansible.com/community/cip

We are live and the Zuul system automatically releases to ansible when we push a new git tag to this repo.

https://ansible.softwarefactory-project.io/zuul/builds?job_name=release-ansible-collection-galaxy
https://ansible.softwarefactory-project.io/zuul/build/e088fd3e74e049bd87ffb07b03fd72b6
